baseURL = "https://tofulab.org/"
title = "tofu website"
theme = "gokarna"
languageCode = "zh-TW"
enableRobotsTXT = true

[pagination]
  pagerSize = 5

[params]
  author = "CHANG-HONGFU"
  description = "一位熱愛資訊的高中生"
  avatarURL = "images/head.jpeg"
  footer = "CHANG-HONGFU"

  # 讓首頁顯示 about.md
  showPostsOnHomePage = true
  showAboutOnHomepage = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/hongfu553"

[[params.socialIcons]]
name = "Instagram"
url = "https://www.instagram.com/tofu_jazz"

[[params.socialIcons]]
name = "spotify"
url = "https://open.spotify.com/user/31hr6cijg4p3coxdgn3bhjnjfcou?si=d52c04d467ad4e62"

[[params.socialIcons]]
name = "discord"
url = "https://discordapp.com/users/726369497136758865"

[[params.socialIcons]]
name = "Email"
url = "mailto:me@tofulab.org"

